#!/usr/bin/env python

import math
import wx
import wx.lib.wxcairo

class MyWindow(wx.Window):
    def __init__(self, *args, **kw):
        wx.Window.__init__(self, *args, **kw)
        self.Bind(wx.EVT_PAINT, self.OnPaint)
        self.Bind(wx.EVT_LEFT_DOWN, self.OnClick)
        self.dots = [(10,10), (100,100)]
    
    def OnPaint(self, e):
        dc = wx.PaintDC(self)
        ctx = wx.lib.wxcairo.ContextFromDC(dc)
        ctx.set_source_rgb(0, 0, 0)
        ctx.paint()
        ctx.set_source_rgb(0, 1, 1)
        for dot in self.dots:
            ctx.arc(dot[0], dot[1], 10, 0, 2*math.pi)
            ctx.close_path()
        ctx.fill()
                
    def OnClick(self, e):
        self.dots.append((e.m_x, e.m_y))
        self.OnPaint(e) # ugly hack!

class MyFrame(wx.Frame):
    def __init__(self, *args, **kw):
        wx.Frame.__init__(self, *args, **kw)
        self.CreateStatusBar()
        filemenu= wx.Menu()
        item = filemenu.Append(wx.ID_ABOUT, "&About..."," Information about this program")
        self.Bind(wx.EVT_MENU, self.OnAbout, item)
        filemenu.AppendSeparator()
        filemenu.Append(wx.ID_EXIT,"E&xit"," Terminate the program")
        # Creating the menubar.
        menuBar = wx.MenuBar()
        menuBar.Append(filemenu,"&File") # Adding the "filemenu" to the MenuBar
        self.SetMenuBar(menuBar)  # Adding the MenuBar to the Frame content.
        MyWindow(self)

    def OnAbout(self, e):
        d = wx.MessageDialog( self, " A sample editor \n"
                            " in wxPython","About Sample Editor", wx.OK)
                            # Create a message dialog box
        d.ShowModal() # Shows it
        d.Destroy() # finally destroy it when finished.

class MyApp(wx.App):
    def OnInit(self):
        frame = MyFrame(None, title="This is a test")
        frame.Show(True)
        self.SetTopWindow(frame)
        return True

def main():
    app = MyApp(0)
    app.MainLoop()

if __name__ == "__main__":
    main()


