#!/usr/bin/env python

from __future__ import division

import math
import wx
from wx.lib.scrolledpanel import ScrolledPanel
import wx.lib.wxcairo
import cairo

import maze

class MyFrame(wx.Frame):
    def __init__(self, *args, **kw):
        wx.Frame.__init__(self, *args, **kw)
        mymaze = maze.Maze(10, 10)
        sash = wx.SplitterWindow(self)
        sp = ScrolledPanel(sash)
        maze.MazeWindow(sp, size=(1000,1000), maze=mymaze)
        sash.SplitVertically(maze.MazeWindow(sash, maze=mymaze), sp)
        sp.SetupScrolling()
        self.CreateStatusBar()
        menuBar = wx.MenuBar()
        filemenu = wx.Menu()
        self.Bind(wx.EVT_MENU, self.OnAbout,
            filemenu.Append(wx.ID_ABOUT, "&About..."," Information about this program"))
        filemenu.AppendSeparator()
        self.Bind(wx.EVT_MENU, self.OnExit,
            filemenu.Append(wx.ID_EXIT,"E&xit"," Terminate the program"))
        menuBar.Append(filemenu,"&File")
        self.SetMenuBar(menuBar)
        toolbar = self.CreateToolBar()
        tsize = (24,24)
        toolbar.SetToolBitmapSize(tsize)
        open_bmp = wx.ArtProvider.GetBitmap(wx.ART_FILE_OPEN, wx.ART_TOOLBAR, tsize)
        toolbar.AddLabelTool(wx.ID_ANY, "Open", open_bmp, shortHelp="Open", longHelp="Long help for 'Open'")
        slider = wx.Slider(toolbar, size=(250,-1))
        toolbar.AddControl(slider)
        

    def OnAbout(self, e):
        d = wx.MessageDialog(self, " A test application \n"
                            " in wxPython","About test app", wx.OK)
        d.ShowModal()
        d.Destroy()

    def OnExit(self, e):
        self.Close(True)

class MyApp(wx.App):
    def OnInit(self):
        frame = MyFrame(None, title="This is a test", size=(880,880))
        frame.Show(True)
        self.SetTopWindow(frame)
        return True

def main():
    app = MyApp(0)
    app.MainLoop()

if __name__ == "__main__":
    main()

